spring:
  application:
    name: service-video

  data:
    mongodb:
      host: localhost
      port: 27017
      database: videodb
      # If your MongoDB doesn't require a username/password, remove or comment out these lines:
      # username: root
      # password: root
      # authentication-database: admin


server:
  port: 8093



info:
  app:
    name: service-video
    desc: This is the video Service for Production Environments in Config Server
    version: 1.0D
