spring:
  application:
    name: service-video

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

  data:
    mongodb:
      host: localhost
      port: 27017
      database: videodb
      # username: root
      # password: root
      # authentication-database: admin

  # profiles:
  #   active: prod      # Change this to dev, qa, or prod as needed


server:
  port: 8093

eureka:

  instance:
    prefer-ip-address: true   # Force IP registration

  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true


info:
  app:
    name: service-video
    desc: This is the Video Service  inside GitHub
    version: "1.0"
